title: <p align="center"> Vishrut Mishra </p>
logo: /assets/img/pic.JPG

description:
    <a href="https://www.linkedin.com/in/vishrut-mishra-220a79a9/">LinkedIn</a> |<a href="https://github.com/shootingStar10">GitHub</a>
    <br> I'm working as a software developer in optical communication domain @Ciena </br>

theme: jekyll-theme-minimal
